"use client"

import { Card, CardContent } from "@/components/ui/card"
import { Star } from "lucide-react"

const testimonials = [
  {
    name: "Dr. Emily Rodriguez",
    role: "Primary Care Physician",
    avatar: "ER",
    content: "Sym has revolutionized how my patients track their symptoms and medications. The detailed reports help me make more informed treatment decisions.",
    rating: 5,
    location: "San Francisco, CA"
  },
  {
    name: "Michael Chen",
    role: "Diabetes Patient",
    avatar: "MC",
    content: "Managing my diabetes has never been easier. The medication reminders and glucose tracking features have helped me maintain better control.",
    rating: 5,
    location: "Austin, TX"
  },
  {
    name: "Sarah Johnson",
    role: "Chronic Pain Patient",
    avatar: "SJ",
    content: "The symptom tracking feature helped me identify patterns I never noticed before. My doctor and I now have a much better understanding of my condition.",
    rating: 5,
    location: "New York, NY"
  },
  {
    name: "James Wilson",
    role: "Senior Citizen",
    avatar: "JW",
    content: "At 72, I was worried about using a health app, but Sym is so intuitive. It helps me keep track of all my medications and appointments.",
    rating: 5,
    location: "Phoenix, AZ"
  },
  {
    name: "Lisa Thompson",
    role: "Working Mother",
    avatar: "LT",
    content: "Sym helps me manage not just my health, but my family's too. The reminder system ensures we never miss important medications or check-ups.",
    rating: 5,
    location: "Chicago, IL"
  },
  {
    name: "Dr. Robert Kim",
    role: "Cardiologist",
    avatar: "RK",
    content: "The health reports generated by Sym provide valuable insights into my patients' daily health patterns, improving our consultation efficiency.",
    rating: 5,
    location: "Los Angeles, CA"
  }
]

export default function Testimonials() {
  return (
    <section className="py-20 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16 animate-fade-in">
          <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Trusted by Thousands
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            See what healthcare professionals and patients are saying about Sym
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {testimonials.map((testimonial, index) => (
            <Card 
              key={index} 
              className="bg-white hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 animate-fade-in"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <CardContent className="p-6">
                <div className="flex items-center space-x-1 mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                  ))}
                </div>
                
                <p className="text-gray-600 mb-6 leading-relaxed italic">
                  "{testimonial.content}"
                </p>
                
                <div className="flex items-center space-x-3">
                  <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-full flex items-center justify-center text-white font-bold">
                    {testimonial.avatar}
                  </div>
                  <div>
                    <div className="font-semibold text-gray-900">{testimonial.name}</div>
                    <div className="text-sm text-gray-500">{testimonial.role}</div>
                    <div className="text-xs text-gray-400">{testimonial.location}</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Trust indicators */}
        <div className="mt-16 text-center space-y-8 animate-fade-in" style={{ animationDelay: '0.8s' }}>
          <div className="grid md:grid-cols-4 gap-8">
            <div className="space-y-2">
              <div className="text-3xl font-bold text-blue-600">50,000+</div>
              <div className="text-gray-600">Active Users</div>
            </div>
            <div className="space-y-2">
              <div className="text-3xl font-bold text-green-600">1M+</div>
              <div className="text-gray-600">Symptoms Tracked</div>
            </div>
            <div className="space-y-2">
              <div className="text-3xl font-bold text-purple-600">500+</div>
              <div className="text-gray-600">Healthcare Providers</div>
            </div>
            <div className="space-y-2">
              <div className="text-3xl font-bold text-orange-600">4.8/5</div>
              <div className="text-gray-600">App Store Rating</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
